version: '3.8'
services:

  dataflow:
    build: 
      context: ./workflow_orchestration/
    restart: always
    networks:
      - backnet
    depends_on:
      - recommenderDB
    volumes:
      -./workflow_orchestration/backups:/usr/src/app/backups
      -./sqlite_db:/usr/src/app/db
    ports:
      -"4200:4200"

  proxy:
    build: 
      context: ./proxy/
    restart: always
    ports:
      - "80:80"
    networks:
      - frontnet

  api:
    build:
      context: ./recommender_api/
    restart: always
    networks:
      - backnet
      - frontnet
    depends_on:
      - proxy
    volumes:
      -./sqlite_db:/usr/src/app/db

networks:
  - frontnet:
  - backnet:
